spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope:
              - profile
              - email

#한글깨짐 설정
server:
  servlet:
    encoding:
      force-response: true


# Test OAuth 설정
