spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc

#한글깨짐 설정
server:
  servlet:
    encoding:
      force-response: true